"use client";

import Image from "next/image";
import { useEffect, useRef, useState } from "react";

const labels={es:{all:"Todas",flores:"Flores",bodas:"Bodas",eventos:"Eventos",personalizados:"Personalizados",more:"Ver más",previous:"Imagen anterior",next:"Imagen siguiente",close:"Cerrar imagen",view:"Ver imagen"},en:{all:"All",flores:"Flowers",bodas:"Weddings",eventos:"Events",personalizados:"Personalized",more:"See more",previous:"Previous image",next:"Next image",close:"Close image",view:"View image"}} as const;
type Category="flores"|"bodas"|"eventos"|"personalizados";
type GalleryImage={id:string;url:string;alt:string;title:string;description:string;category:Category;featured:boolean};

export function PortfolioGallery({items,locale}:{items:GalleryImage[];locale:"es"|"en"}){
  const copy=labels[locale];const [category,setCategory]=useState<"all"|Category>("all");const [shown,setShown]=useState(12);const [selected,setSelected]=useState<number|null>(null);const trigger=useRef<HTMLButtonElement|null>(null);const touchStart=useRef<number|null>(null);
  const availableCategories=(["flores","bodas","eventos","personalizados"] as const).filter(value=>items.some(item=>item.category===value));const filtered=items.filter(item=>category==="all"||item.category===category);const visible=filtered.slice(0,shown);const selectedItem=selected===null?undefined:filtered[selected];
  const selectCategory=(value:"all"|Category)=>{setCategory(value);setShown(12);setSelected(null);};
  const move=(direction:number)=>setSelected(current=>current===null?null:(current+direction+filtered.length)%filtered.length);
  useEffect(()=>{if(selected===null)return;const handle=(event:KeyboardEvent)=>{if(event.key==="Escape")setSelected(null);if(event.key==="ArrowLeft")move(-1);if(event.key==="ArrowRight")move(1);};window.addEventListener("keydown",handle);return()=>window.removeEventListener("keydown",handle);},[selected,filtered.length]);
  useEffect(()=>{if(selectedItem)return;trigger.current?.focus();},[selectedItem]);
  if(!items.length)return null;
  return <section className="portfolio-gallery" aria-label={locale==="es"?"Galería floral":"Floral gallery"}>{availableCategories.length>2&&<div className="portfolio-gallery-filters" role="tablist" aria-label={locale==="es"?"Filtrar galería":"Filter gallery"}>{(["all",...availableCategories] as Array<"all"|Category>).map(value=>{const count=value==="all"?items.length:items.filter(item=>item.category===value).length;return <button key={value} type="button" role="tab" aria-selected={category===value} className={category===value?"is-active":""} onClick={()=>selectCategory(value)}>{copy[value]} ({count})</button>;})}</div>}<div className="portfolio-gallery-grid">{visible.map((item,index)=><article key={item.id} className={`portfolio-gallery-card${item.featured&&index===0?" is-featured":""}`}><button type="button" className="portfolio-gallery-image" aria-label={`${copy.view}: ${item.title}`} onClick={event=>{trigger.current=event.currentTarget;setSelected(index);}}><Image src={item.url} alt={item.alt} fill sizes={item.featured&&index===0?"(max-width: 760px) 100vw, (max-width: 1200px) 66vw, 50vw":"(max-width: 760px) 100vw, (max-width: 1200px) 50vw, 33vw"}/><span className="portfolio-gallery-overlay"><strong>{item.title}</strong><small>{copy.view} →</small></span></button>{item.featured&&index===0&&<span className="portfolio-gallery-featured">★ {locale==="es"?"Destacada":"Featured"}</span>}</article>)}</div>{shown<filtered.length&&<div className="portfolio-gallery-more"><button type="button" onClick={()=>setShown(current=>current+12)}>{copy.more}</button></div>}{selectedItem&&<div className="portfolio-lightbox" role="dialog" aria-modal="true" aria-label={selectedItem.title} onTouchStart={event=>{touchStart.current=event.touches[0]?.clientX??null;}} onTouchEnd={event=>{if(touchStart.current===null)return;const delta=(event.changedTouches[0]?.clientX??touchStart.current)-touchStart.current;if(Math.abs(delta)>40)move(delta<0?1:-1);touchStart.current=null;}}><button type="button" className="portfolio-lightbox-backdrop" aria-label={copy.close} onClick={()=>setSelected(null)}/><div className="portfolio-lightbox-content"><Image src={selectedItem.url} alt={selectedItem.alt} fill sizes="100vw" priority/><button type="button" className="portfolio-lightbox-close" aria-label={copy.close} autoFocus onClick={()=>setSelected(null)}>×</button>{filtered.length>1&&<><button type="button" className="portfolio-lightbox-arrow is-previous" aria-label={copy.previous} onClick={()=>move(-1)}>‹</button><button type="button" className="portfolio-lightbox-arrow is-next" aria-label={copy.next} onClick={()=>move(1)}>›</button></>}<div className="portfolio-lightbox-copy"><span>{copy[selectedItem.category]}</span><strong>{selectedItem.title}</strong>{selectedItem.description&&<p>{selectedItem.description}</p>}</div></div></div>}</section>;
}
