import { sql } from "drizzle-orm";
import { boolean, check, index, integer, jsonb, pgEnum, pgTable, primaryKey, text, timestamp, uniqueIndex, uuid } from "drizzle-orm/pg-core";

const timestamps = { createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull() };
export const productType = pgEnum("product_type", ["floral", "complement", "personalized"]);
export const productStatus = pgEnum("product_status", ["draft", "active", "archived"]);
export const inquiryStatus = pgEnum("inquiry_status", ["new", "reviewing", "quoting", "quoted", "approved", "rejected", "completed"]);
export const orderStatus = pgEnum("order_status", ["draft", "pending", "confirmed", "preparing", "ready", "delivered", "cancelled"]);
export const fulfillmentMode = pgEnum("fulfillment_mode", ["delivery", "pickup"]);
export const foundationChecks = pgTable("foundation_checks", {
  id: uuid("id").defaultRandom().primaryKey(),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
});

export const roles = pgTable("roles", { id: uuid("id").defaultRandom().primaryKey(), code: text("code").notNull().unique(), name: text("name").notNull() });
export const users = pgTable("users", { id: uuid("id").defaultRandom().primaryKey(), email: text("email").notNull(), passwordHash: text("password_hash"), externalIdentity: text("external_identity"), active: boolean("active").default(true).notNull(), ...timestamps }, t => [uniqueIndex("users_email_lower_unique").on(sql`lower(${t.email})`), check("users_identity_required", sql`${t.passwordHash} IS NOT NULL OR ${t.externalIdentity} IS NOT NULL`)]);
export const userRoles = pgTable("user_roles", { userId: uuid("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), roleId: uuid("role_id").notNull().references(() => roles.id, { onDelete: "cascade" }) }, t => [primaryKey({ columns: [t.userId, t.roleId] }), index("user_roles_role_idx").on(t.roleId)]);
export const customers = pgTable("customers", { id: uuid("id").defaultRandom().primaryKey(), identityKey: text("identity_key"), name: text("name").notNull(), email: text("email"), phone: text("phone"), contactPreference: text("contact_preference"), ...timestamps }, t => [check("customers_contact_required", sql`${t.email} IS NOT NULL OR ${t.phone} IS NOT NULL`), uniqueIndex("customers_identity_unique").on(t.identityKey), index("customers_email_idx").on(t.email), index("customers_phone_idx").on(t.phone)]);
export const categories = pgTable("categories", { id: uuid("id").defaultRandom().primaryKey(), name: text("name").notNull(), slug: text("slug").notNull().unique(), description: text("description"), sortOrder: integer("sort_order").default(0).notNull(), visible: boolean("visible").default(true).notNull(), ...timestamps }, t => [index("categories_navigation_idx").on(t.visible, t.sortOrder)]);
export const mediaAssets = pgTable("media_assets", { id: uuid("id").defaultRandom().primaryKey(), provider: text("provider").notNull(), providerId: text("provider_id").notNull(), url: text("url").notNull(), width: integer("width"), height: integer("height"), bytes: integer("bytes"), format: text("format"), alt: text("alt"), visibility: text("visibility").default("public").notNull(), ...timestamps }, t => [uniqueIndex("media_assets_provider_id_unique").on(t.provider, t.providerId), check("media_assets_visibility_check", sql`${t.visibility} IN ('public', 'private')`)]);
export const products = pgTable("products", { id: uuid("id").defaultRandom().primaryKey(), categoryId: uuid("category_id").references(() => categories.id, { onDelete: "set null" }), name: text("name").notNull(), slug: text("slug").notNull().unique(), type: productType("type").notNull(), shortDescription: text("short_description"), description: text("description"), basePrice: integer("base_price").notNull(), priceLabel: text("price_label"), status: productStatus("status").default("draft").notNull(), featured: boolean("featured").default(false).notNull(), customizable: boolean("customizable").default(false).notNull(), ...timestamps }, t => [index("products_catalog_idx").on(t.status, t.type, t.categoryId), check("products_price_nonnegative", sql`${t.basePrice} >= 0`)]);
export const productImages = pgTable("product_images", { id: uuid("id").defaultRandom().primaryKey(), productId: uuid("product_id").notNull().references(() => products.id, { onDelete: "cascade" }), mediaAssetId: uuid("media_asset_id").notNull().references(() => mediaAssets.id, { onDelete: "restrict" }), sortOrder: integer("sort_order").default(0).notNull(), primary: boolean("primary").default(false).notNull() }, t => [uniqueIndex("product_images_asset_unique").on(t.productId, t.mediaAssetId), uniqueIndex("product_images_one_primary").on(t.productId).where(sql`${t.primary} = true`), index("product_images_order_idx").on(t.productId, t.sortOrder)]);
export const productVariants = pgTable("product_variants", { id: uuid("id").defaultRandom().primaryKey(), productId: uuid("product_id").notNull().references(() => products.id, { onDelete: "cascade" }), name: text("name").notNull(), attributes: jsonb("attributes").$type<Record<string, string>>().default({}).notNull(), price: integer("price").notNull(), available: boolean("available").default(true).notNull(), stockOnHand: integer("stock_on_hand"), sortOrder: integer("sort_order").default(0).notNull(), ...timestamps }, t => [index("product_variants_order_idx").on(t.productId, t.sortOrder), check("product_variants_price_nonnegative", sql`${t.price} >= 0`), check("product_variants_stock_nonnegative", sql`${t.stockOnHand} IS NULL OR ${t.stockOnHand} >= 0`)]);
export const productComplementRecommendations = pgTable("product_complement_recommendations", { floralProductId: uuid("floral_product_id").notNull().references(() => products.id, { onDelete: "cascade" }), complementProductId: uuid("complement_product_id").notNull().references(() => products.id, { onDelete: "cascade" }), sortOrder: integer("sort_order").default(0).notNull(), active: boolean("active").default(true).notNull(), ...timestamps }, t => [primaryKey({ columns: [t.floralProductId, t.complementProductId] }), index("product_complements_order_idx").on(t.floralProductId, t.active, t.sortOrder), check("product_complements_distinct", sql`${t.floralProductId} <> ${t.complementProductId}`)]);
export const combos = pgTable("combos", { id: uuid("id").defaultRandom().primaryKey(), name: text("name").notNull(), slug: text("slug").notNull().unique(), description: text("description"), imageUrl: text("image_url"), price: integer("price").notNull(), promotionalPrice: integer("promotional_price"), startsAt: timestamp("starts_at", { withTimezone: true }), endsAt: timestamp("ends_at", { withTimezone: true }), featured: boolean("featured").default(false).notNull(), active: boolean("active").default(true).notNull(), ...timestamps }, t => [index("combos_public_idx").on(t.active, t.featured, t.startsAt, t.endsAt), check("combos_prices_check", sql`${t.price} >= 0 AND (${t.promotionalPrice} IS NULL OR (${t.promotionalPrice} >= 0 AND ${t.promotionalPrice} <= ${t.price}))`), check("combos_dates_check", sql`${t.startsAt} IS NULL OR ${t.endsAt} IS NULL OR ${t.startsAt} < ${t.endsAt}`)]);
export const comboItems = pgTable("combo_items", { id: uuid("id").defaultRandom().primaryKey(), comboId: uuid("combo_id").notNull().references(() => combos.id, { onDelete: "cascade" }), productId: uuid("product_id").notNull().references(() => products.id, { onDelete: "restrict" }), variantId: uuid("variant_id").references(() => productVariants.id, { onDelete: "set null" }), quantity: integer("quantity").default(1).notNull() }, t => [index("combo_items_combo_idx").on(t.comboId), check("combo_items_quantity_check", sql`${t.quantity} > 0`)]);
export const services = pgTable("services", { id: uuid("id").defaultRandom().primaryKey(), name: text("name").notNull(), slug: text("slug").notNull().unique(), type: text("type").notNull(), description: text("description"), imageId: uuid("image_id").references(() => mediaAssets.id, { onDelete: "set null" }), visible: boolean("visible").default(true).notNull(), sortOrder: integer("sort_order").default(0).notNull(), ...timestamps }, t => [index("services_navigation_idx").on(t.visible, t.sortOrder)]);
export const galleryItems = pgTable("gallery_items", { id: uuid("id").defaultRandom().primaryKey(), title: text("title").notNull(), slug: text("slug").notNull().unique(), categoryId: uuid("category_id").references(() => categories.id, { onDelete: "set null" }), eventDate: timestamp("event_date", { withTimezone: true }), description: text("description"), featured: boolean("featured").default(false).notNull(), visible: boolean("visible").default(true).notNull(), sortOrder: integer("sort_order").default(0).notNull(), ...timestamps }, t => [index("gallery_items_order_idx").on(t.visible, t.sortOrder)]);
export const galleryImages = pgTable("gallery_images", { id: uuid("id").defaultRandom().primaryKey(), galleryItemId: uuid("gallery_item_id").notNull().references(() => galleryItems.id, { onDelete: "cascade" }), mediaAssetId: uuid("media_asset_id").notNull().references(() => mediaAssets.id, { onDelete: "restrict" }), sortOrder: integer("sort_order").default(0).notNull() }, t => [uniqueIndex("gallery_images_asset_unique").on(t.galleryItemId, t.mediaAssetId), index("gallery_images_order_idx").on(t.galleryItemId, t.sortOrder)]);
export const inquiries = pgTable("inquiries", { id: uuid("id").defaultRandom().primaryKey(), reference: text("reference").notNull().unique(), idempotencyKey: text("idempotency_key"), customerId: uuid("customer_id").notNull().references(() => customers.id, { onDelete: "restrict" }), type: text("type").notNull(), occasion: text("occasion"), style: text("style"), colors: text("colors").array(), budgetMin: integer("budget_min"), budgetMax: integer("budget_max"), requiredAt: timestamp("required_at", { withTimezone: true }), fulfillment: fulfillmentMode("fulfillment"), notes: text("notes"), internalNotes: text("internal_notes"), status: inquiryStatus("status").default("new").notNull(), notificationStatus: text("notification_status").default("pending").notNull(), notificationError: text("notification_error"), notificationAttempts: integer("notification_attempts").default(0).notNull(), ...timestamps }, t => [index("inquiries_status_date_idx").on(t.status, t.createdAt), index("inquiries_customer_idx").on(t.customerId), uniqueIndex("inquiries_idempotency_unique").on(t.idempotencyKey), check("inquiries_notification_status_check", sql`${t.notificationStatus} IN ('pending', 'sent', 'failed')`), check("inquiries_budget_check", sql`(${t.budgetMin} IS NULL OR ${t.budgetMin} >= 0) AND (${t.budgetMax} IS NULL OR ${t.budgetMax} >= 0) AND (${t.budgetMin} IS NULL OR ${t.budgetMax} IS NULL OR ${t.budgetMin} <= ${t.budgetMax})`)]);
export const inquiryImages = pgTable("inquiry_images", { id: uuid("id").defaultRandom().primaryKey(), inquiryId: uuid("inquiry_id").notNull().references(() => inquiries.id, { onDelete: "cascade" }), mediaAssetId: uuid("media_asset_id").notNull().references(() => mediaAssets.id, { onDelete: "restrict" }), sortOrder: integer("sort_order").default(0).notNull() }, t => [index("inquiry_images_order_idx").on(t.inquiryId, t.sortOrder)]);
export const orders = pgTable("orders", { id: uuid("id").defaultRandom().primaryKey(), reference: text("reference").notNull().unique(), idempotencyKey: text("idempotency_key"), customerId: uuid("customer_id").notNull().references(() => customers.id, { onDelete: "restrict" }), inquiryId: uuid("inquiry_id").references(() => inquiries.id, { onDelete: "set null" }), requiredAt: timestamp("required_at", { withTimezone: true }), fulfillment: fulfillmentMode("fulfillment").notNull(), deliveryAddress: text("delivery_address"), subtotal: integer("subtotal").default(0).notNull(), deliveryFee: integer("delivery_fee").default(0).notNull(), total: integer("total").default(0).notNull(), deposit: integer("deposit").default(0).notNull(), balance: integer("balance").default(0).notNull(), paymentMethod: text("payment_method"), paymentStatus: text("payment_status").default("unpaid").notNull(), stripeSessionId: text("stripe_session_id"), paymentProofAssetId: uuid("payment_proof_asset_id").references(() => mediaAssets.id, { onDelete: "set null" }), trackingToken: text("tracking_token").notNull().unique(), status: orderStatus("status").default("draft").notNull(), ...timestamps }, t => [index("orders_status_date_idx").on(t.status, t.createdAt), index("orders_customer_idx").on(t.customerId), uniqueIndex("orders_idempotency_unique").on(t.idempotencyKey), uniqueIndex("orders_stripe_session_unique").on(t.stripeSessionId), check("orders_payment_method_check", sql`${t.paymentMethod} IS NULL OR ${t.paymentMethod} IN ('stripe', 'sinpe')`), check("orders_payment_status_check", sql`${t.paymentStatus} IN ('unpaid', 'pending_review', 'paid', 'failed', 'refunded')`), check("orders_amounts_check", sql`${t.subtotal} >= 0 AND ${t.deliveryFee} >= 0 AND ${t.total} = ${t.subtotal} + ${t.deliveryFee} AND ${t.deposit} >= 0 AND ${t.deposit} <= ${t.total} AND ${t.balance} = ${t.total} - ${t.deposit}`), check("orders_delivery_address_check", sql`${t.fulfillment} <> 'delivery' OR ${t.deliveryAddress} IS NOT NULL`)]);
export const orderItems = pgTable("order_items", { id: uuid("id").defaultRandom().primaryKey(), orderId: uuid("order_id").notNull().references(() => orders.id, { onDelete: "cascade" }), productId: uuid("product_id").references(() => products.id, { onDelete: "set null" }), variantId: uuid("variant_id").references(() => productVariants.id, { onDelete: "set null" }), comboId: uuid("combo_id").references(() => combos.id, { onDelete: "set null" }), nameSnapshot: text("name_snapshot").notNull(), unitPriceSnapshot: integer("unit_price_snapshot").notNull(), quantity: integer("quantity").notNull(), personalization: jsonb("personalization").$type<Record<string, unknown>>(), lineTotal: integer("line_total").notNull() }, t => [index("order_items_order_idx").on(t.orderId), check("order_items_source_check", sql`num_nonnulls(${t.productId}, ${t.comboId}) = 1`), check("order_items_amounts_check", sql`${t.unitPriceSnapshot} >= 0 AND ${t.quantity} > 0 AND ${t.lineTotal} = ${t.unitPriceSnapshot} * ${t.quantity}`)]);
export const orderInventoryItems = pgTable("order_inventory_items", { orderId: uuid("order_id").notNull().references(() => orders.id, { onDelete: "cascade" }), variantId: uuid("variant_id").notNull().references(() => productVariants.id, { onDelete: "restrict" }), quantity: integer("quantity").notNull() }, t => [primaryKey({ columns: [t.orderId, t.variantId] }), index("order_inventory_variant_idx").on(t.variantId), check("order_inventory_quantity_check", sql`${t.quantity} > 0`)]);
export const events = pgTable("events", { id: uuid("id").defaultRandom().primaryKey(), title: text("title").notNull(), type: text("type").notNull(), customerId: uuid("customer_id").references(() => customers.id, { onDelete: "set null" }), startsAt: timestamp("starts_at", { withTimezone: true }).notNull(), venue: text("venue"), status: text("status").default("planned").notNull(), notes: text("notes"), ...timestamps }, t => [index("events_date_idx").on(t.startsAt), check("events_status_check", sql`${t.status} IN ('planned', 'confirmed', 'completed', 'cancelled')`)]);
export const testimonials = pgTable("testimonials", { id: uuid("id").defaultRandom().primaryKey(), displayName: text("display_name").notNull(), quote: text("quote").notNull(), imageId: uuid("image_id").references(() => mediaAssets.id, { onDelete: "set null" }), approved: boolean("approved").default(false).notNull(), sortOrder: integer("sort_order").default(0).notNull(), ...timestamps }, t => [index("testimonials_public_idx").on(t.approved, t.sortOrder)]);
export const homepageSections = pgTable("homepage_sections", { id: uuid("id").defaultRandom().primaryKey(), key: text("key").notNull().unique(), visible: boolean("visible").default(true).notNull(), sortOrder: integer("sort_order").default(0).notNull(), content: jsonb("content").$type<Record<string, unknown>>().default({}).notNull(), startsAt: timestamp("starts_at", { withTimezone: true }), endsAt: timestamp("ends_at", { withTimezone: true }), ...timestamps }, t => [index("homepage_sections_order_idx").on(t.visible, t.sortOrder), check("homepage_sections_dates_check", sql`${t.startsAt} IS NULL OR ${t.endsAt} IS NULL OR ${t.startsAt} < ${t.endsAt}`)]);
export const siteSettings = pgTable("site_settings", { key: text("key").primaryKey(), value: jsonb("value").$type<Record<string, unknown>>().notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull() });
export const rateLimits = pgTable("rate_limits", { key: text("key").primaryKey(), count: integer("count").default(0).notNull(), resetAt: timestamp("reset_at", { withTimezone: true }).notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull() }, t => [index("rate_limits_reset_idx").on(t.resetAt)]);
