"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import { formatCRC } from "@/lib/format";
import { useStore } from "./store-provider";
import type { Locale } from "@/lib/i18n";

type GiftProduct = { id: string; slug: string; name: string; basePrice: number; image: string | null; variants: { id: string; name: string; price: number }[] };
type Complement = { id: string; slug: string; name: string; basePrice: number; image: string | null };

export function GiftBuilder({ flowers, complements, locale }: { flowers: GiftProduct[]; complements: Complement[]; locale:Locale }) {
  const es=locale==="es";
  const { addItem } = useStore();
  const [step, setStep] = useState(0); const [flowerId, setFlowerId] = useState(flowers[0]?.id ?? ""); const [variantId, setVariantId] = useState(flowers[0]?.variants[0]?.id ?? "");
  const [style, setStyle] = useState(""); const [selectedComplements, setSelectedComplements] = useState<string[]>([]); const [dedication, setDedication] = useState(""); const [fulfillment, setFulfillment] = useState("delivery"); const [date, setDate] = useState(""); const [added, setAdded] = useState(false);
  const flower = flowers.find(item => item.id === flowerId); const variant = flower?.variants.find(item => item.id === variantId) ?? flower?.variants[0];
  const chosenComplements = complements.filter(item => selectedComplements.includes(item.id));
  const total = (variant?.price ?? flower?.basePrice ?? 0) + chosenComplements.reduce((sum, item) => sum + item.basePrice, 0);
  const canContinue = step !== 0 || Boolean(flower); const minDate = useMemo(() => new Date().toISOString().slice(0, 10), []);
  const chooseFlower = (id: string) => { setFlowerId(id); setVariantId(flowers.find(item => item.id === id)?.variants[0]?.id ?? ""); };
  const addGift = () => { if (!flower) return; const details = [style && `${es?"Estilo":"Style"}: ${style}`, dedication && `${es?"Dedicatoria":"Message"}: ${dedication}`, date && `${es?"Fecha":"Date"}: ${date}`, fulfillment === "delivery" ? (es?"Entrega":"Delivery") : (es?"Retiro":"Pickup")].filter(Boolean).join(" · "); addItem({ kind: "product", productId: flower.id, variantId: variant?.id, slug: flower.slug, name: flower.name, price: variant?.price ?? flower.basePrice, image: flower.image, quantity: 1, personalization: details }); chosenComplements.forEach(item => addItem({ kind: "product", productId: item.id, slug: item.slug, name: item.name, price: item.basePrice, image: item.image, quantity: 1 })); setAdded(true); };
  return <div className="gift-builder"><ol className="gift-progress" aria-label={es?"Progreso":"Progress"}>{(es?["Flores","Estilo","Detalles","Revisión"]:["Flowers","Style","Details","Review"]).map((label,index)=><li className={index===step?"is-current":index<step?"is-complete":""} key={label}>{index+1}. {label}</li>)}</ol>
    {step===0&&<section><h2>{es?"Elige las flores y el tamaño":"Choose the flowers and size"}</h2><label>{es?"Arreglo":"Arrangement"}<select value={flowerId} onChange={event=>chooseFlower(event.target.value)}>{flowers.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label>{flower?.variants.length?<label>{es?"Tamaño":"Size"}<select value={variant?.id} onChange={event=>setVariantId(event.target.value)}>{flower.variants.map(item=><option key={item.id} value={item.id}>{item.name} · {formatCRC(item.price)}</option>)}</select></label>:<p>{es?"Este arreglo se prepara en presentación estándar.":"This arrangement is prepared in a standard presentation."}</p>}</section>}
    {step===1&&<section><h2>{es?"Define el estilo":"Choose the style"}</h2><label>{es?"Estilo o color":"Style or color"}<input value={style} onChange={event=>setStyle(event.target.value)} placeholder={es?"Romántico, natural, rosado…":"Romantic, natural, blush…"} maxLength={120}/></label><fieldset className="complement-options"><legend>{es?"Complementos":"Extras"}</legend>{complements.length?complements.map(item=><label key={item.id}><input type="checkbox" checked={selectedComplements.includes(item.id)} onChange={()=>setSelectedComplements(current=>current.includes(item.id)?current.filter(id=>id!==item.id):[...current,item.id])}/><span>{item.name}</span><strong>{formatCRC(item.basePrice)}</strong></label>):<p>{es?"No hay complementos disponibles por ahora.":"No extras are available right now."}</p>}</fieldset></section>}
    {step===2&&<section><h2>{es?"Dedicatoria y entrega":"Message and delivery"}</h2><label>{es?"Dedicatoria":"Message"}<textarea value={dedication} onChange={event=>setDedication(event.target.value)} maxLength={400}/></label><label>{es?"Modalidad":"Method"}<select value={fulfillment} onChange={event=>setFulfillment(event.target.value)}><option value="delivery">{es?"Entrega":"Delivery"}</option><option value="pickup">{es?"Retiro":"Pickup"}</option></select></label><label>{es?"Fecha requerida":"Required date"}<input type="date" min={minDate} value={date} onChange={event=>setDate(event.target.value)}/></label></section>}
    {step===3&&<section><h2>{es?"Revisa tu regalo":"Review your gift"}</h2><dl className="gift-review"><div><dt>{es?"Flores":"Flowers"}</dt><dd>{flower?.name} · {variant?.name??(es?"Estándar":"Standard")}</dd></div><div><dt>{es?"Estilo":"Style"}</dt><dd>{style||(es?"A criterio floral":"Florist's choice")}</dd></div><div><dt>{es?"Complementos":"Extras"}</dt><dd>{chosenComplements.map(item=>item.name).join(", ")||(es?"Sin complementos":"No extras")}</dd></div><div><dt>{es?"Modalidad":"Method"}</dt><dd>{fulfillment==="delivery"?(es?"Entrega":"Delivery"):(es?"Retiro":"Pickup")}{date?` · ${date}`:""}</dd></div><div><dt>{es?"Total estimado":"Estimated total"}</dt><dd>{formatCRC(total)}</dd></div></dl>{added?<p role="status">{es?"Regalo agregado.":"Gift added."} <Link href="/carrito">{es?"Ver carrito":"View cart"}</Link></p>:<button type="button" className="commerce-primary" onClick={addGift}>{es?"Agregar regalo al carrito":"Add gift to cart"}</button>}</section>}
    <div className="gift-controls"><button type="button" disabled={step===0} onClick={()=>setStep(current=>current-1)}>{es?"Atrás":"Back"}</button>{step<3&&<button type="button" className="commerce-primary" disabled={!canContinue} onClick={()=>setStep(current=>current+1)}>{es?"Continuar":"Continue"}</button>}</div>
  </div>;
}
