"use client";
import { Input, InputNumber, Typography } from "antd";
import { saveBusinessSettings } from "@/app/admin/actions";
import { AdminFormGrid, AdminFormSection } from "./admin-form-section";
import { ValidatedAdminForm } from "./validated-admin-form";
type Values={email:string;phone:string;whatsapp:string;instagram:string;facebook:string;hoursEn:string;hoursEs:string;deliveryArea:string;deliveryNoticeEn:string;deliveryNoticeEs:string;deliveryFee:number;depositPercent:number;cancellationPolicyEn:string;cancellationPolicyEs:string;privacyRetentionEn:string;privacyRetentionEs:string};
type FieldProps={label:string;name:string;value:string|number;area?:boolean;number?:boolean;max?:number};
const requiredFields=new Set(["email","phone","whatsapp","deliveryArea","hoursEn","hoursEs"]);
const Field=({label,name,value,area=false,number=false,max=100}:FieldProps)=><label><span>{label}{requiredFields.has(name)&&<em>*</em>}</span>{area?<Input.TextArea name={name} defaultValue={String(value)} placeholder={`Escribe ${label.toLowerCase()}`} rows={3}/>:number?<InputNumber name={name} defaultValue={Number(value)} placeholder="0" min={0} max={max} style={{width:"100%"}}/>:<Input name={name} defaultValue={String(value)} placeholder={`Escribe ${label.toLowerCase()}`}/>}</label>;
export function BusinessSettingsForm({value}:{value:Values}){return <ValidatedAdminForm action={saveBusinessSettings} required={["email","phone","whatsapp","deliveryArea","hoursEn","hoursEs"]} email={["email"]} submitLabel="Guardar configuración"><Typography.Text type="secondary">Contacto, condiciones y textos públicos editables por idioma.</Typography.Text><AdminFormSection number="1" title="Contacto" text="Canales que tus clientes pueden utilizar para comunicarse."><AdminFormGrid><Field label="Correo" name="email" value={value.email}/><Field label="Teléfono" name="phone" value={value.phone}/><Field label="WhatsApp" name="whatsapp" value={value.whatsapp}/><Field label="Instagram" name="instagram" value={value.instagram}/><Field label="Facebook" name="facebook" value={value.facebook}/></AdminFormGrid></AdminFormSection><AdminFormSection number="2" title="Servicio y entrega" text="Horarios, cobertura y condiciones visibles durante la compra."><AdminFormGrid><Field label="Horario en español" name="hoursEs" value={value.hoursEs} area/><Field label="Horario en inglés" name="hoursEn" value={value.hoursEn} area/><Field label="Zona de entrega" name="deliveryArea" value={value.deliveryArea}/><Field label="Costo de entrega (CRC)" name="deliveryFee" value={value.deliveryFee} number max={1_000_000}/><Field label="Aviso de entrega en español" name="deliveryNoticeEs" value={value.deliveryNoticeEs} area/><Field label="Aviso de entrega en inglés" name="deliveryNoticeEn" value={value.deliveryNoticeEn} area/><Field label="Adelanto requerido (%)" name="depositPercent" value={value.depositPercent} number/></AdminFormGrid></AdminFormSection><AdminFormSection number="3" title="Políticas" text="Información comercial y de privacidad disponible para tus clientes."><AdminFormGrid><Field label="Cancelaciones y devoluciones en español" name="cancellationPolicyEs" value={value.cancellationPolicyEs} area/><Field label="Cancelaciones y devoluciones en inglés" name="cancellationPolicyEn" value={value.cancellationPolicyEn} area/><Field label="Conservación de datos en español" name="privacyRetentionEs" value={value.privacyRetentionEs} area/><Field label="Conservación de datos en inglés" name="privacyRetentionEn" value={value.privacyRetentionEn} area/></AdminFormGrid></AdminFormSection></ValidatedAdminForm>}
