"use client";

import { Image, Upload } from "antd";
import type { UploadProps } from "antd";
import { DeleteOutlined, PictureOutlined, UploadOutlined } from "@ant-design/icons";
import { useEffect, useRef, useState } from "react";
import { saveGalleryItem } from "@/app/admin/actions";
import { AdminFormGrid, AdminFormSection } from "./admin-form-section";
import { ValidatedAdminForm } from "./validated-admin-form";

type GalleryItem = { id: string; title: string; description: string | null; sortOrder: number; featured: boolean };

function slugify(value: string) { return value.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().trim().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, ""); }
async function compressImage(file: File) { if (!file.type.startsWith("image/") || file.size < 300_000) return file; try { const image = await createImageBitmap(file); const scale = Math.min(1, 1600 / Math.max(image.width, image.height)); const canvas = document.createElement("canvas"); canvas.width = Math.round(image.width * scale); canvas.height = Math.round(image.height * scale); canvas.getContext("2d")?.drawImage(image, 0, 0, canvas.width, canvas.height); image.close(); const blob = await new Promise<Blob | null>(resolve => canvas.toBlob(resolve, "image/webp", .82)); return blob ? new File([blob], `${file.name.replace(/\.[^.]+$/, "")}.webp`, { type: "image/webp" }) : file; } catch { return file; } }

export function GalleryForm({ editing, suggestedOrder, initialImageUrl = "" }: { editing?: GalleryItem; suggestedOrder: number; initialImageUrl?: string }) {
  const [title, setTitle] = useState(editing?.title ?? ""); const [preview, setPreview] = useState(initialImageUrl); const [imageFile, setImageFile] = useState<File>(); const previewUrl = useRef(""); const slug = slugify(title);
  useEffect(() => () => { if (previewUrl.current) URL.revokeObjectURL(previewUrl.current); }, []);
  const beforeUpload: UploadProps["beforeUpload"] = async file => { const compressed = await compressImage(file as File); if (previewUrl.current) URL.revokeObjectURL(previewUrl.current); const url = URL.createObjectURL(compressed); previewUrl.current = url; setImageFile(compressed); setPreview(url); return Upload.LIST_IGNORE; };
  const clearImage = (event: React.MouseEvent<HTMLButtonElement>) => { event.preventDefault(); event.stopPropagation(); if (previewUrl.current) URL.revokeObjectURL(previewUrl.current); previewUrl.current = ""; setImageFile(undefined); setPreview(""); };
  return <ValidatedAdminForm action={saveGalleryItem} required={["title", "slug"]} submitLabel={editing ? "Guardar cambios" : "Crear publicación"} className="admin-form product-form gallery-form" encType="multipart/form-data" prepareFormData={formData => { if (imageFile) formData.set("imageFile", imageFile); return formData; }}>
    {editing && <input type="hidden" name="id" value={editing.id}/>} 
    <div className="product-form-layout"><div className="product-form-main"><AdminFormSection number="1" title="Información básica" text="Define el título, URL y descripción de la publicación."><AdminFormGrid><label><span>Título <em>*</em></span><input name="title" value={title} onChange={event => setTitle(event.target.value)} placeholder="Ej. Arreglo de temporada" required/></label><label><span>Identificador URL <em>*</em></span><input name="slug" value={slug} readOnly placeholder="Se genera desde el título"/><small>Se genera automáticamente a partir del título.</small></label></AdminFormGrid><label><span>Descripción</span><textarea name="description" defaultValue={editing?.description ?? ""} placeholder="Describe la publicación..." maxLength={2000}/></label></AdminFormSection><AdminFormSection number="2" title="Orden y visibilidad" text="Controla la posición y relevancia de la publicación."><AdminFormGrid><label><span>Orden</span><input name="sortOrder" type="number" defaultValue={editing?.sortOrder ?? suggestedOrder} min="0" placeholder="0" required/></label><label className="admin-checkbox-field gallery-form-visibility"><input name="featured" type="checkbox" defaultChecked={editing?.featured}/> <span>Publicación destacada</span></label></AdminFormGrid></AdminFormSection></div><aside className="product-form-media"><AdminFormSection number="3" title="Imagen de la publicación" text="Agrega una fotografía atractiva para la galería."><Upload.Dragger className={`product-image-dropzone${preview ? " has-preview" : ""}`} accept="image/jpeg,image/png,image/webp" maxCount={1} showUploadList={false} beforeUpload={beforeUpload}>{preview ? <div className="product-image-selected"><Image src={preview} alt="Vista previa de la publicación" preview={false}/><div className="product-image-selected-overlay"><PictureOutlined/><strong>Imagen seleccionada</strong><span>Haz clic para cambiarla</span><button type="button" className="product-image-remove" onClick={clearImage}><DeleteOutlined/> Eliminar imagen</button></div></div> : <><PictureOutlined/><strong>Arrastra una imagen aquí</strong><span>o haz clic para seleccionar</span><button type="button"><UploadOutlined/> Seleccionar imagen</button></>}<small>JPG, PNG o WebP. Se comprime automáticamente.</small></Upload.Dragger></AdminFormSection></aside></div>
  </ValidatedAdminForm>;
}
