"use client";
import { saveHeroCopy } from "@/app/admin/actions";
import type { HeroCopy } from "@/lib/hero-copy";
import { useEffect, useState } from "react";
import { AdminFormGrid, AdminFormSection } from "./admin-form-section";
import { ValidatedAdminForm } from "./validated-admin-form";

const fields=["eyebrowEs","eyebrowEn","titleEs","titleEn","emphasisEs","emphasisEn","descriptionEs","descriptionEn","primaryLabelEs","primaryLabelEn","primaryHref","secondaryLabelEs","secondaryLabelEn","secondaryHref","asideEs","asideEn"];
function Field({name,label,value,area=false}:{name:keyof HeroCopy;label:string;value:string;area?:boolean}){return <label><span>{label} <em>*</em></span>{area?<textarea name={name} defaultValue={value} placeholder={`Escribe ${label.toLowerCase()}`} rows={3}/>:<input name={name} defaultValue={value} placeholder={name.endsWith("Href")?"#seccion o /ruta":`Escribe ${label.toLowerCase()}`}/>}</label>}
export function HeroCopySettingsForm({value}:{value:HeroCopy}){const[visible,setVisible]=useState(false);useEffect(()=>{const onTab=(event:Event)=>setVisible((event as CustomEvent<string>).detail==="hero");window.addEventListener("identity-tab-change",onTab);return()=>window.removeEventListener("identity-tab-change",onTab)},[]);return <section className="admin-panel hero-copy-panel" hidden={!visible} aria-hidden={!visible}><h2>Contenido de la portada</h2><ValidatedAdminForm action={saveHeroCopy} required={fields} submitLabel="Guardar contenido"><div className="hero-copy-grid"><AdminFormSection number="1" title="Español" text="Textos que se muestran cuando el sitio está en español."><Field name="eyebrowEs" label="Antetítulo" value={value.eyebrowEs}/><Field name="titleEs" label="Primera línea del título" value={value.titleEs}/><Field name="emphasisEs" label="Línea destacada del título" value={value.emphasisEs}/><Field name="descriptionEs" label="Descripción" value={value.descriptionEs} area/><Field name="primaryLabelEs" label="Botón principal" value={value.primaryLabelEs}/><Field name="secondaryLabelEs" label="Botón secundario" value={value.secondaryLabelEs}/><Field name="asideEs" label="Frase inferior" value={value.asideEs}/></AdminFormSection><AdminFormSection number="2" title="English" text="Copy shown when the website is in English."><Field name="eyebrowEn" label="Eyebrow" value={value.eyebrowEn}/><Field name="titleEn" label="First title line" value={value.titleEn}/><Field name="emphasisEn" label="Highlighted title line" value={value.emphasisEn}/><Field name="descriptionEn" label="Description" value={value.descriptionEn} area/><Field name="primaryLabelEn" label="Primary button" value={value.primaryLabelEn}/><Field name="secondaryLabelEn" label="Secondary button" value={value.secondaryLabelEn}/><Field name="asideEn" label="Bottom phrase" value={value.asideEn}/></AdminFormSection></div><AdminFormSection number="3" title="Enlaces de los botones" text="Usa una sección existente como #historia o una ruta como /flores."><AdminFormGrid><Field name="primaryHref" label="Destino del botón principal" value={value.primaryHref}/><Field name="secondaryHref" label="Destino del botón secundario" value={value.secondaryHref}/></AdminFormGrid></AdminFormSection></ValidatedAdminForm></section>}
