"use client";

import { DeleteOutlined, DesktopOutlined, EditOutlined, MobileOutlined, PictureOutlined, PlayCircleOutlined, UploadOutlined, VideoCameraOutlined } from "@ant-design/icons";
import { App, Button, Collapse, ColorPicker, Input as AntInput, Segmented, Tabs, Typography } from "antd";
import { useFormik } from "formik";
import Image from "next/image";
import { useEffect, useMemo, useRef, useState } from "react";
import * as yup from "yup";
import { saveBrandingSettings } from "@/app/admin/actions";
type BrandingSettings={brandName:string;logoUrl:string;logoAltEs:string;logoAltEn:string;faviconUrl:string;heroVideoUrl:string;heroImageUrl:string;heroImageAltEs:string;heroImageAltEn:string;backgroundColor:string;foregroundColor:string;primaryColor:string;accentColor:string;softAccentColor:string};

type FileKey = "logo" | "favicon" | "heroImage" | "heroVideo";
type HeroMode = "image" | "youtube" | "upload";
function Input(props:React.ComponentProps<typeof AntInput>){return <AntInput placeholder="Escribe aquí" {...props}/>}
const paletteKeys=["backgroundColor","foregroundColor","primaryColor","accentColor","softAccentColor"] as const;
const originalBranding={logoUrl:"/orosblooms-logo.png",faviconUrl:"/icon.svg",backgroundColor:"#faf8f4",foregroundColor:"#292b25",primaryColor:"#59654d",accentColor:"#744448",softAccentColor:"#f8ebec"};
const initialPalette=Object.fromEntries(paletteKeys.map(key=>[key,originalBranding[key]]));
const palettes={"Floral OrosBlooms":initialPalette,"Rosa editorial":{backgroundColor:"#FFF9F6",foregroundColor:"#342A2A",primaryColor:"#685D50",accentColor:"#A45168",softAccentColor:"#F9E6EC"},"Verde natural":{backgroundColor:"#F7F8F2",foregroundColor:"#28322A",primaryColor:"#4B654C",accentColor:"#99705F",softAccentColor:"#E8F0E3"},"Minimalista":{backgroundColor:"#FAFAF8",foregroundColor:"#292929",primaryColor:"#4C4C48",accentColor:"#777066",softAccentColor:"#F0EFEB"}};
const schema=yup.object({brandName:yup.string().trim().min(2,"Escribe al menos 2 caracteres").max(80).required("El nombre es obligatorio"),logoAltEs:yup.string().trim().required("Describe el logotipo en español"),logoAltEn:yup.string().trim().required("Describe el logotipo en inglés"),heroImageAltEs:yup.string().trim().required("Describe la imagen en español"),heroImageAltEn:yup.string().trim().required("Describe la imagen en inglés")});
function youtubeEmbedUrl(url:string){try{const parsed=new URL(url);const id=parsed.hostname.includes("youtu.be")?parsed.pathname.slice(1):parsed.searchParams.get("v")??(parsed.pathname.startsWith("/embed/")?parsed.pathname.split("/")[2]:null);return id&&/^[\w-]{11}$/.test(id)?`https://www.youtube-nocookie.com/embed/${id}?autoplay=1&mute=1&loop=1&playlist=${id}&controls=0&playsinline=1&rel=0`:null;}catch{return null;}}
function detectMode(value:BrandingSettings):HeroMode{return youtubeEmbedUrl(value.heroVideoUrl)?"youtube":value.heroVideoUrl.includes("/videos/")||value.heroVideoUrl.includes("/uploads/")?"upload":"image"}

export function IdentitySettingsForm({value}:{value:BrandingSettings}){
  const {message}=App.useApp();const [files,setFiles]=useState<Partial<Record<FileKey,File>>>({});const [tab,setTab]=useState("brand");const [preview,setPreview]=useState<"desktop"|"mobile">("desktop");const [heroMode,setHeroMode]=useState<HeroMode>(detectMode(value));const [saving,setSaving]=useState(false);const inputs=useRef<Partial<Record<FileKey,HTMLInputElement|null>>>({});
  useEffect(()=>{window.dispatchEvent(new CustomEvent("identity-tab-change",{detail:tab}));},[tab]);
  const formik=useFormik({initialValues:value,validationSchema:schema,onSubmit:async values=>{setSaving(true);try{const data=new FormData();Object.entries(values).forEach(([key,entry])=>data.set(key,entry));Object.entries(files).forEach(([key,file])=>data.set(key,file));await saveBrandingSettings(data);message.success("Cambios publicados correctamente.");}catch(error){message.error(error instanceof Error?error.message:"No se pudo publicar.");}finally{setSaving(false);}}});
  const previews=useMemo(()=>Object.fromEntries(Object.entries(files).map(([key,file])=>[key,URL.createObjectURL(file)])) as Partial<Record<FileKey,string>>,[files]);const logoSrc=previews.logo??formik.values.logoUrl;const faviconSrc=previews.favicon??formik.values.faviconUrl;const heroImage=previews.heroImage??formik.values.heroImageUrl;const heroVideo=previews.heroVideo??formik.values.heroVideoUrl;const youtubeUrl=youtubeEmbedUrl(heroVideo);const dirty=formik.dirty||Object.keys(files).length>0;
  const rules:Record<FileKey,{types:string[];max:number;label:string}>={logo:{types:["image/png","image/webp","image/svg+xml"],max:8_000_000,label:"PNG, WebP o SVG · máximo 8 MB"},favicon:{types:["image/png","image/x-icon","image/vnd.microsoft.icon","image/svg+xml"],max:2_000_000,label:"PNG, ICO o SVG · máximo 2 MB"},heroImage:{types:["image/jpeg","image/png","image/webp"],max:12_000_000,label:"JPG, PNG o WebP · máximo 12 MB"},heroVideo:{types:["video/mp4","video/webm"],max:40_000_000,label:"MP4 o WebM · máximo 40 MB"}};
  const choose=(key:FileKey)=>inputs.current[key]?.click();const selectFile=(key:FileKey,file?:File)=>{if(!file)return;const rule=rules[key];if(!rule.types.includes(file.type)||file.size>rule.max){message.error(`Archivo no compatible. Usa ${rule.label}.`);return;}setFiles(current=>({...current,[key]:file}));if(key==="heroVideo"){formik.setFieldValue("heroVideoUrl","");setHeroMode("upload");}if(key==="heroImage")formik.setFieldValue("heroImageUrl","");};const discard=()=>{formik.resetForm();setFiles({});setHeroMode(detectMode(value));message.info("Cambios descartados.");};const fileInput=(key:FileKey,accept:string)=><input ref={node=>{inputs.current[key]=node;}} className="identity-hidden-input" type="file" accept={accept} onChange={event=>selectFile(key,event.currentTarget.files?.[0])}/>;
  const asset=({title,description,key,src,accept}:{title:string;description:string;key:"logo"|"favicon";src:string;accept:string})=><section className="identity-card"><div><Typography.Title level={5}>{title}</Typography.Title><Typography.Text type="secondary">{description}</Typography.Text></div><div className={`identity-asset ${key==="favicon"?"is-icon":""}`}><Image src={src} alt="" fill unoptimized/></div><div className="identity-card-actions"><Button icon={<EditOutlined/>} onClick={()=>choose(key)}>Cambiar {key==="logo"?"logo":"ícono"}</Button><Button type="text" icon={<DeleteOutlined/>} onClick={()=>formik.setFieldValue(key==="logo"?"logoUrl":"faviconUrl",key==="logo"?originalBranding.logoUrl:originalBranding.faviconUrl)}>Restaurar original</Button></div>{files[key]&&<Typography.Text type="secondary">Seleccionado: {files[key]!.name}</Typography.Text>}{fileInput(key,accept)}<small>{rules[key].label}</small></section>;
  const heroOption=(mode:HeroMode,icon:React.ReactNode,title:string,text:string)=><button type="button" className={`identity-hero-option ${heroMode===mode?"is-active":""}`} onClick={()=>{setHeroMode(mode);if(mode!=="youtube")formik.setFieldValue("heroVideoUrl",mode==="image"?"":formik.values.heroVideoUrl);if(mode!=="upload")setFiles(current=>{const next={...current};delete next.heroVideo;return next;});}}><span>{icon}</span><strong>{title}</strong><small>{text}</small></button>;
  const previewStyle={"--preview-bg":formik.values.backgroundColor,"--preview-fg":formik.values.foregroundColor,"--preview-primary":formik.values.primaryColor,"--preview-accent":formik.values.accentColor,"--preview-soft":formik.values.softAccentColor} as React.CSSProperties;const previewMedia=heroMode==="image"?<Image src={heroImage} alt={formik.values.heroImageAltEs} fill unoptimized/>:youtubeUrl?<iframe src={youtubeUrl} title="Video de portada" allow="autoplay; encrypted-media; picture-in-picture"/>:heroVideo?<video src={heroVideo} poster={heroImage} muted autoPlay loop playsInline/>:<Image src={heroImage} alt={formik.values.heroImageAltEs} fill unoptimized/>;
  return <form onSubmit={formik.handleSubmit} className="identity-redesign admin-pattern-form"><div className="identity-tabs"><Tabs activeKey={tab} onChange={setTab} items={[{key:"brand",label:"Marca"},{key:"colors",label:"Colores"},{key:"hero",label:"Portada"}]}/></div><div className="identity-layout"><section className="identity-config">
    {tab==="brand"&&<div className="identity-stack"><header><Typography.Title level={4}>Configuración de marca</Typography.Title><Typography.Text type="secondary">Los elementos esenciales que verán tus clientes.</Typography.Text></header><section className="identity-card"><Typography.Title level={5}>Nombre de la marca</Typography.Title><Typography.Text type="secondary">Este es el nombre que verán tus clientes.</Typography.Text><Input name="brandName" value={formik.values.brandName} onChange={formik.handleChange} onBlur={formik.handleBlur} status={formik.touched.brandName&&formik.errors.brandName?"error":""}/></section>{asset({title:"Logotipo",description:"Se mostrará en la navegación y otras áreas de la página.",key:"logo",src:logoSrc,accept:"image/png,image/webp,image/svg+xml"})}{asset({title:"Ícono del navegador",description:"Se muestra en la pestaña del navegador.",key:"favicon",src:faviconSrc,accept:"image/png,image/x-icon,image/vnd.microsoft.icon,image/svg+xml"})}<Collapse items={[{key:"accessibility",label:"Accesibilidad",children:<div className="identity-accessibility"><label>Texto alternativo en español<Input name="logoAltEs" value={formik.values.logoAltEs} onChange={formik.handleChange}/></label><label>Texto alternativo en inglés<Input name="logoAltEn" value={formik.values.logoAltEn} onChange={formik.handleChange}/></label></div>}]}/></div>}
    {tab==="colors"&&<div className="identity-stack"><header><Typography.Title level={4}>Colores de la marca</Typography.Title><Typography.Text type="secondary">Estos colores se aplicarán en toda la experiencia pública de OrosBlooms.</Typography.Text></header><section><Typography.Text strong>Paletas sugeridas</Typography.Text><div className="identity-palettes">{Object.entries(palettes).map(([name,palette])=><button type="button" key={name} onClick={()=>Object.entries(palette).forEach(([key,color])=>formik.setFieldValue(key,color))}><span>{Object.values(palette).map(color=><i key={color} style={{background:color}}/>)}</span>{name}</button>)}</div></section><section className="identity-card identity-colors">{([['backgroundColor','Fondo'],['foregroundColor','Texto'],['primaryColor','Primario'],['accentColor','Acento'],['softAccentColor','Acento suave']] as const).map(([name,label])=><label key={name}><span>{label}</span><ColorPicker value={formik.values[name]} onChange={color=>formik.setFieldValue(name,color.toHexString().toUpperCase())}/><Input value={formik.values[name]} onChange={event=>formik.setFieldValue(name,event.target.value.toUpperCase())}/></label>)}</section><Button type="text" onClick={()=>Object.entries(initialPalette).forEach(([key,color])=>formik.setFieldValue(key,color))}>Restablecer paleta original</Button></div>}
    {tab==="hero"&&<div className="identity-stack"><header><Typography.Title level={4}>Portada del inicio</Typography.Title><Typography.Text type="secondary">Elige qué quieres mostrar como imagen principal de OrosBlooms.</Typography.Text></header><div className="identity-hero-options">{heroOption("image",<PictureOutlined/>,"Solo imagen","Una fotografía")}{heroOption("youtube",<PlayCircleOutlined/>,"Video de YouTube","Usa un enlace")}{heroOption("upload",<VideoCameraOutlined/>,"Subir video","MP4 o WebM")}</div>{heroMode==="youtube"&&<section className="identity-card"><Typography.Title level={5}>Enlace del video</Typography.Title><Input value={formik.values.heroVideoUrl} placeholder="https://youtube.com/..." onChange={event=>{formik.setFieldValue("heroVideoUrl",event.target.value);setFiles(current=>{const next={...current};delete next.heroVideo;return next;});}}/>{youtubeEmbedUrl(formik.values.heroVideoUrl)&&<Typography.Text type="success">✓ Video detectado</Typography.Text>}</section>}{heroMode==="upload"&&<section className="identity-card"><Typography.Title level={5}>Video de portada</Typography.Title><MediaThumb src={heroVideo} video/><Button icon={<UploadOutlined/>} onClick={()=>choose("heroVideo")}>Cambiar video</Button>{files.heroVideo&&<Typography.Text type="secondary">Seleccionado: {files.heroVideo.name}</Typography.Text>}{fileInput("heroVideo","video/mp4,video/webm")}<small>{rules.heroVideo.label}</small></section>}<section className="identity-card"><Typography.Title level={5}>{heroMode==="image"?"Imagen de portada":"Imagen de respaldo"}</Typography.Title><Typography.Text type="secondary">{heroMode==="image"?"La imagen principal de tu inicio.":"Se muestra mientras el video carga o si no puede reproducirse."}</Typography.Text><MediaThumb src={heroImage}/><Button icon={<UploadOutlined/>} onClick={()=>choose("heroImage")}>Cambiar imagen</Button>{files.heroImage&&<Typography.Text type="secondary">Seleccionado: {files.heroImage.name}</Typography.Text>}{fileInput("heroImage","image/jpeg,image/png,image/webp")}<small>{rules.heroImage.label}</small></section><Collapse items={[{key:"hero-accessibility",label:"Accesibilidad de imagen",children:<div className="identity-accessibility"><label>Texto alternativo en español<Input name="heroImageAltEs" value={formik.values.heroImageAltEs} onChange={formik.handleChange}/></label><label>Texto alternativo en inglés<Input name="heroImageAltEn" value={formik.values.heroImageAltEn} onChange={formik.handleChange}/></label></div>}]}/></div>}
  </section><aside className={`identity-live-preview is-${preview}`} style={previewStyle}><header><div><strong>Vista previa</strong><small>{dirty?"● Cambios sin publicar":"✓ Todo está publicado"}</small></div><Segmented value={preview} onChange={value=>setPreview(value as "desktop"|"mobile")} options={[{value:"desktop",icon:<DesktopOutlined/>},{value:"mobile",icon:<MobileOutlined/>}]}/></header><div className="identity-preview-frame"><div className="identity-preview-header"><Image src={logoSrc} alt="" width={150} height={46} unoptimized/><nav>Inicio&nbsp;&nbsp; Flores&nbsp;&nbsp; Bodas</nav></div><div className="identity-preview-hero"><div className="identity-preview-copy"><small>FLORES PARA CADA HISTORIA</small><h2>Diseños que<br/><em>hacen sentir.</em></h2><p>Arreglos únicos para momentos reales.</p><button type="button">Explorar diseños</button></div><div className="identity-preview-visual">{previewMedia}</div></div></div></aside></div><div className="identity-publish-bar"><span className={dirty?"is-dirty":""}>{dirty?"● Cambios sin publicar":"✓ Todo está publicado"}</span><div><Button onClick={discard} disabled={!dirty}>Descartar</Button><Button type="primary" htmlType="submit" loading={saving} disabled={!dirty}>Guardar y publicar</Button></div></div></form>;
}
function MediaThumb({src,video=false}:{src:string;video?:boolean}){return <div className="identity-media-thumb">{video?<video src={src} muted playsInline/>:<Image src={src} alt="" fill unoptimized/>}</div>}
