"use client";
import { DeleteOutlined, SearchOutlined, SaveOutlined } from "@ant-design/icons";
import { App, Button, Input, Popconfirm, Select, Space, Table, Tag, Tooltip } from "antd";
import { useMemo, useState } from "react";
import { deleteInquiry, deleteOrder, saveOrder, updateInquiry } from "@/app/admin/actions";
import { formatCRC } from "@/lib/format";

type Inquiry={id:string;reference:string;status:string;type:string;notes:string|null;internalNotes:string|null;createdAt:string;customer:string;phone:string|null};
type Order={id:string;reference:string;status:string;total:number;customer:string};
const inquiryLabels:Record<string,string>={new:"Nueva",reviewing:"En revisión",quoting:"Cotizando",quoted:"Cotizada",approved:"Aprobada",rejected:"Rechazada",completed:"Completada"};
const orderLabels:Record<string,string>={draft:"Borrador",pending:"Pendiente",confirmed:"Confirmado",preparing:"Preparando",ready:"Listo",delivered:"Entregado",cancelled:"Cancelado"};
const inquiryStatuses=Object.entries(inquiryLabels).map(([value,label])=>({value,label}));const orderStatuses=Object.entries(orderLabels).map(([value,label])=>({value,label}));

export function InquiryTable({items}:{items:Inquiry[]}){const{message}=App.useApp();const[query,setQuery]=useState("");const[status,setStatus]=useState<string>();const[changes,setChanges]=useState<Record<string,{status:string;notes:string}>>({});const data=useMemo(()=>items.filter(item=>(!status||item.status===status)&&`${item.reference} ${item.customer} ${item.phone??""} ${item.type}`.toLowerCase().includes(query.toLowerCase())),[items,query,status]);const save=async(item:Inquiry)=>{const edit=changes[item.id]??{status:item.status,notes:item.internalNotes??""};const form=new FormData();form.set("id",item.id);form.set("status",edit.status);form.set("internalNotes",edit.notes);await updateInquiry(form);message.success("Solicitud actualizada.");};const remove=async(id:string)=>{const form=new FormData();form.set("id",id);await deleteInquiry(form);message.success("Solicitud eliminada.");};return <><div className="admin-table-toolbar"><Input prefix={<SearchOutlined/>} placeholder="Buscar referencia, cliente o tipo" value={query} onChange={event=>setQuery(event.target.value)} allowClear/><Select placeholder="Todos los estados" value={status} onChange={setStatus} options={inquiryStatuses} allowClear/></div><Table rowKey="id" dataSource={data} pagination={{pageSize:10,showSizeChanger:true}} scroll={{x:900}} columns={[{title:"Referencia",dataIndex:"reference",render:(value,item)=><>{value}<br/><small>{new Date(item.createdAt).toLocaleDateString("es-CR")}</small></>},{title:"Cliente",dataIndex:"customer",render:(value,item)=><>{value}<br/><small>{item.phone}</small></>},{title:"Solicitud",dataIndex:"type",render:(value,item)=><>{value}<br/><small>{item.notes}</small></>},{title:"Estado",render:(_,item)=><Select style={{minWidth:145}} value={changes[item.id]?.status??item.status} options={inquiryStatuses} onChange={value=>setChanges(current=>({...current,[item.id]:{status:value,notes:current[item.id]?.notes??item.internalNotes??""}}))}/>},{title:"Nota interna",render:(_,item)=><Input.TextArea placeholder="Escribe una nota interna" value={changes[item.id]?.notes??item.internalNotes??""} onChange={event=>setChanges(current=>({...current,[item.id]:{status:current[item.id]?.status??item.status,notes:event.target.value}}))}/>},{title:"Acciones",fixed:"right",render:(_,item)=><Space><Tooltip title="Guardar"><Button shape="circle" type="text" icon={<SaveOutlined/>} onClick={()=>save(item)}/></Tooltip><Popconfirm title="Eliminar solicitud" description="Esta acción no se puede deshacer." onConfirm={()=>remove(item.id)}><Button shape="circle" type="text" danger icon={<DeleteOutlined/>}/></Popconfirm></Space>}]}/></>}

export function OrderTable({items}:{items:Order[]}){const{message}=App.useApp();const[query,setQuery]=useState("");const[filter,setFilter]=useState<string>();const[changes,setChanges]=useState<Record<string,string>>({});const data=useMemo(()=>items.filter(item=>(!filter||item.status===filter)&&`${item.reference} ${item.customer}`.toLowerCase().includes(query.toLowerCase())),[items,query,filter]);const save=async(item:Order)=>{const form=new FormData();form.set("id",item.id);form.set("status",changes[item.id]??item.status);await saveOrder(form);message.success("Pedido actualizado.");};const remove=async(id:string)=>{const form=new FormData();form.set("id",id);await deleteOrder(form);message.success("Pedido eliminado.");};return <><div className="admin-table-toolbar"><Input prefix={<SearchOutlined/>} placeholder="Buscar pedido o cliente" value={query} onChange={event=>setQuery(event.target.value)} allowClear/><Select placeholder="Todos los estados" value={filter} onChange={setFilter} options={orderStatuses} allowClear/></div><Table rowKey="id" dataSource={data} pagination={{pageSize:10,showSizeChanger:true}} columns={[{title:"Pedido",dataIndex:"reference",render:(value,item)=><>{value}<br/><small>{item.customer}</small></>},{title:"Total",dataIndex:"total",render:value=>formatCRC(value)},{title:"Estado",render:(_,item)=><Select style={{minWidth:150}} value={changes[item.id]??item.status} options={orderStatuses} onChange={value=>setChanges(current=>({...current,[item.id]:value}))}/>},{title:"Situación",dataIndex:"status",render:value=><Tag color={value==="cancelled"?"red":value==="delivered"?"green":"default"}>{orderLabels[value]}</Tag>},{title:"Acciones",render:(_,item)=><Space><Tooltip title="Guardar"><Button shape="circle" type="text" icon={<SaveOutlined/>} onClick={()=>save(item)}/></Tooltip><Popconfirm title="Eliminar pedido" description="Esta acción no se puede deshacer." onConfirm={()=>remove(item.id)}><Button shape="circle" type="text" danger icon={<DeleteOutlined/>}/></Popconfirm></Space>}]}/></>}
