"use client";
import { Alert, App, Button } from "antd";
import { useFormik } from "formik";
import { unstable_rethrow } from "next/navigation";
import * as yup from "yup";
import { useEffect, useRef, useState } from "react";

type Props={action:(formData:FormData)=>void|Promise<void>;children:React.ReactNode;required?:string[];email?:string[];submitLabel?:string;className?:string;encType?:string;onSuccess?:()=>void;prepareFormData?:(formData:FormData)=>FormData};
function serverError(error: unknown) { const message=error instanceof Error?error.message:"No se pudo guardar. Revisa los datos e inténtalo nuevamente."; const match=/^\[field:([^\]]+)\]\s*(.*)$/.exec(message); if(match)return{field:match[1],message:match[2]};const internal=/failed query|insert into|update .* returning|params:|drizzle/i.test(message);return{field:"form",message:internal?"No se pudo guardar en este momento. Inténtalo nuevamente.":message}; }
export function ValidatedAdminForm({action,children,required=[],email=[],submitLabel="Guardar",className="admin-form",encType,onSuccess,prepareFormData}:Props){
  const { message: toast }=App.useApp();const formRef=useRef<HTMLFormElement>(null); const [message,setMessage]=useState("");
  useEffect(()=>{const form=formRef.current;if(!form)return;required.forEach(name=>{const field=form.elements.namedItem(name);if(field instanceof HTMLInputElement||field instanceof HTMLTextAreaElement||field instanceof HTMLSelectElement)field.required=true;});email.forEach(name=>{const field=form.elements.namedItem(name);if(field instanceof HTMLInputElement)field.type="email";});},[required,email]);
  const formik=useFormik<Record<string,string>>({initialValues:{},onSubmit:async()=>{const form=formRef.current;if(!form)return;const controls=Array.from(form.elements).filter((control):control is HTMLInputElement|HTMLTextAreaElement|HTMLSelectElement=>control instanceof HTMLInputElement||control instanceof HTMLTextAreaElement||control instanceof HTMLSelectElement);const invalid=controls.filter(control=>!control.checkValidity());if(invalid.length){const errors=Object.fromEntries(invalid.filter(control=>control.name).map(control=>[control.name,control.validationMessage]));form.dispatchEvent(new CustomEvent("form:errors",{bubbles:true,detail:{errors}}));setMessage("Revisa los campos marcados antes de guardar.");return;}const values=Object.fromEntries(new FormData(form).entries());const shape:Record<string,yup.StringSchema>={};required.forEach(name=>shape[name]=yup.string().trim().required("Este campo es obligatorio"));email.forEach(name=>shape[name]=yup.string().trim().email("Ingresa un correo válido").required("Este campo es obligatorio"));try{await yup.object(shape).validate(values,{abortEarly:false});setMessage("");await action(prepareFormData?.(new FormData(form))??new FormData(form));toast.success("Guardado correctamente.");form.dispatchEvent(new CustomEvent("form:success",{bubbles:true}));onSuccess?.();}catch(error){unstable_rethrow(error);if(error instanceof yup.ValidationError){const errors=Object.fromEntries(error.inner.map(item=>[item.path??"form",item.message]));formik.setErrors(errors);form.dispatchEvent(new CustomEvent("form:errors",{bubbles:true,detail:{errors}}));setMessage("Revisa los campos marcados antes de guardar.");return;}const server=serverError(error);if(server.field!=="form"){const errors={[server.field]:server.message};formik.setErrors(errors);form.dispatchEvent(new CustomEvent("form:errors",{bubbles:true,detail:{errors}}));}setMessage(server.message);}}});
  return <form ref={formRef} className={`${className} admin-pattern-form validated-admin-form`} encType={encType} onSubmit={formik.handleSubmit} noValidate>{message&&<Alert type="error" showIcon message={message}/>}<div className="admin-form-fields">{children}</div><Button type="primary" htmlType="submit" loading={formik.isSubmitting} disabled={formik.isSubmitting}>{submitLabel}</Button></form>;
}
