import { and, asc, desc, eq, ilike, or, sql } from "drizzle-orm"; import { notFound } from "next/navigation"; import { db } from "@/db/client"; import { categories,comboItems,combos,customers,galleryImages,galleryItems,homepageSections,inquiries,mediaAssets,orderItems,orders,productImages,products,productVariants,siteSettings } from "@/db/schema"; import { deleteCombo,deleteCustomer,deleteGalleryItem,deleteMediaAsset,saveCustomer,saveOrder,uploadMedia } from "../actions"; import { formatCRC } from "@/lib/format"; import { testBusinessSettings,type BusinessSettings } from "@/lib/business"; import { BusinessSettingsForm } from "@/components/admin/business-settings-form"; import { IdentitySettingsForm } from "@/components/admin/identity-settings-form"; import { HomepageSectionForm } from "@/components/admin/homepage-section-form"; import { AdminRecordActions } from "@/components/admin/admin-record-actions"; import { defaultBrandingSettings,type BrandingSettings } from "@/lib/branding";
import { ProductAssetsEditor } from "@/components/admin/product-assets-editor";
import { ProductAssetsModal } from "@/components/admin/product-assets-modal";
import { ProductTable } from "@/components/admin/product-table";
import { CategoryManager } from "@/components/admin/category-manager";
import { ServiceManager } from "@/components/admin/service-manager";
import { AdminDataTable } from "@/components/admin/admin-data-table";
import { AdminFormModal } from "@/components/admin/admin-form-modal";
import { ProductForm } from "@/components/admin/product-form";
import { ComboForm } from "@/components/admin/combo-form";
import { GalleryForm } from "@/components/admin/gallery-form";
import { ValidatedAdminForm } from "@/components/admin/validated-admin-form";
import { homepageSectionDefaults, homepageSectionKeys } from "@/lib/homepage";
import { SeoPoliciesForm } from "@/components/admin/seo-policies-form";
import { InquiryTable, OrderTable } from "@/components/admin/operations-tables";
import { services } from "@/db/schema";
import { HeroCopySettingsForm } from "@/components/admin/hero-copy-settings-form";
import { AdminFormGrid, AdminFormSection } from "@/components/admin/admin-form-section";
import { defaultHeroCopy, type HeroCopy } from "@/lib/hero-copy";
import type { ServicePageContent } from "@/lib/service-page";
import { requireAdmin } from "@/lib/admin-auth";
import { PageContentManager } from "@/components/admin/page-content-manager";
import { HomepageContentManager } from "@/components/admin/homepage-content-manager";
import { defaultPageContent, pageSlugs, type PageContent, type PageImage, type PageSlug } from "@/lib/service-page";
const sections=["identidad","categorias","productos","combos","galeria","servicios","paginas","solicitudes","clientes","pedidos","inicio","multimedia","seo-politicas","configuracion"];
export default async function AdminSection({params,searchParams}:{params:Promise<{section:string}>;searchParams:Promise<Record<string,string|string[]|undefined>>}){await requireAdmin();const{section}=await params;const queryParams=await searchParams;const editId=Array.isArray(queryParams.edit)?queryParams.edit[0]:queryParams.edit;const assetId=Array.isArray(queryParams.assets)?queryParams.assets[0]:queryParams.assets;if(!sections.includes(section))notFound();
if(section==="identidad"){const[brandingRows,heroRows]=await Promise.all([db.select({value:siteSettings.value}).from(siteSettings).where(eq(siteSettings.key,"branding")).limit(1),db.select({value:siteSettings.value}).from(siteSettings).where(eq(siteSettings.key,"hero-copy")).limit(1)]);const value={...defaultBrandingSettings,...(brandingRows[0]?.value as Partial<BrandingSettings>|undefined)};const heroCopy={...defaultHeroCopy,...(heroRows[0]?.value as Partial<HeroCopy>|undefined)};return <><Head title="Identidad visual" text="Personaliza la marca, los colores y la portada de OrosBlooms."/><IdentitySettingsForm value={value}/><HeroCopySettingsForm value={heroCopy}/></>}
if(section==="categorias"){const items=await db.select().from(categories).orderBy(asc(categories.sortOrder),asc(categories.name));return <><Head title="Categorías" text="Organiza la navegación del catálogo sin eliminar productos asociados."/><CategoryManager items={items}/></>}
if(section==="productos"){const selectedProductId=assetId??editId;const[items,cats,variants,imageRows,productImageRows,productVariantRows]=await Promise.all([db.select().from(products).orderBy(desc(products.updatedAt)),db.select().from(categories).orderBy(asc(categories.sortOrder)),selectedProductId?db.select().from(productVariants).where(eq(productVariants.productId,selectedProductId)).orderBy(asc(productVariants.sortOrder)):Promise.resolve([]),selectedProductId?db.select({id:productImages.id,url:mediaAssets.url,alt:mediaAssets.alt,primary:productImages.primary,sortOrder:productImages.sortOrder}).from(productImages).innerJoin(mediaAssets,eq(productImages.mediaAssetId,mediaAssets.id)).where(eq(productImages.productId,selectedProductId)).orderBy(asc(productImages.sortOrder)):Promise.resolve([]),db.select({productId:productImages.productId,url:mediaAssets.url}).from(productImages).innerJoin(mediaAssets,eq(productImages.mediaAssetId,mediaAssets.id)).where(eq(productImages.primary,true)),db.select({productId:productVariants.productId}).from(productVariants)]);const editing=items.find(item=>item.id===editId);const assetProduct=items.find(item=>item.id===assetId);return <><Head title="Productos" text="Crea, edita y organiza el catálogo floral."/><div className="admin-grid"><Panel title={editing?"Editar producto":"Nuevo producto"}><ProductForm editing={editing} categories={cats.map(category=>({id:category.id,name:category.name}))} initialImageUrl={editing?imageRows[0]?.url??"":""}/></Panel><ProductTable items={items} categories={cats.map(category=>({id:category.id,name:category.name}))} images={productImageRows} variants={productVariantRows}/></div>{assetProduct&&<ProductAssetsModal productName={assetProduct.name}><ProductAssetsEditor productId={assetProduct.id} variants={variants} images={imageRows}/></ProductAssetsModal>}</>}
if(section==="combos"){const[items,productItems,included]=await Promise.all([db.select().from(combos).orderBy(desc(combos.updatedAt)),db.select().from(products).where(eq(products.status,"active")).orderBy(asc(products.name)),editId?db.select().from(comboItems).where(eq(comboItems.comboId,editId)):Promise.resolve([])]);const editing=items.find(item=>item.id===editId);const selectedProducts=new Set(included.map(item=>item.productId));return <><Head title="Combos" text="Crea, edita y administra composiciones promocionales."/><div className="admin-grid"><Panel title={editing?"Editar combo":"Nuevo combo"}><ComboForm editing={editing} products={productItems} selectedProducts={selectedProducts}/></Panel><AdminDataTable columns={["Combo","Precio","Estado","Acciones"]} rows={items.map(item=>({id:item.id,cells:[{primary:item.name,secondary:item.slug},item.promotionalPrice?`${formatCRC(item.promotionalPrice)} (antes ${formatCRC(item.price)})`:formatCRC(item.price),{primary:item.active?"Activo":"Inactivo",tone:item.active?"active" as const:"inactive" as const}],searchText:`${item.name} ${item.slug}`,filterValue:item.active?"active":"inactive",editHref:`/admin/combos?edit=${item.id}`}))} noun="combos" searchPlaceholder="Buscar combos..." filterPlaceholder="Todos los estados" filterOptions={[{value:"active",label:"Activo"},{value:"inactive",label:"Inactivo"}]} deleteAction={deleteCombo}/></div></>}
if(section==="galeria"){const[items,imageRows]=await Promise.all([db.select().from(galleryItems).orderBy(asc(galleryItems.sortOrder)),editId?db.select({id:galleryImages.id,url:mediaAssets.url}).from(galleryImages).innerJoin(mediaAssets,eq(galleryImages.mediaAssetId,mediaAssets.id)).where(eq(galleryImages.galleryItemId,editId)).orderBy(asc(galleryImages.sortOrder)):Promise.resolve([])]);const editing=items.find(item=>item.id===editId);const suggestedOrder=(items.at(-1)?.sortOrder??-1)+1;const categoryLabels={flores:"Flores",bodas:"Bodas",eventos:"Eventos",personalizados:"Personalizados"} as const;return <><Head title="Galería" text="Administra las fotografías y el orden del portafolio floral."/><div className="admin-grid"><Panel title={editing?"Editar publicación":"Nueva publicación"}><GalleryForm editing={editing} suggestedOrder={suggestedOrder} initialImages={imageRows}/></Panel><AdminDataTable columns={["Publicación","Categoría","Estado","Orden","Acciones"]} rows={items.map(item=>({id:item.id,cells:[{primary:item.title,secondary:item.slug},categoryLabels[item.galleryCategory as keyof typeof categoryLabels]??"Flores",{primary:item.visible?"Visible":"Oculta",tone:item.visible?"active" as const:"inactive" as const},item.sortOrder],searchText:`${item.title} ${item.slug} ${item.galleryCategory}`,filterValue:item.galleryCategory,editHref:`/admin/galeria?edit=${item.id}`}))} noun="publicaciones" searchPlaceholder="Buscar publicaciones..." filterPlaceholder="Todas las categorías" filterOptions={[{value:"flores",label:"Flores"},{value:"bodas",label:"Bodas"},{value:"eventos",label:"Eventos"},{value:"personalizados",label:"Personalizados"}]} deleteAction={deleteGalleryItem}/></div></>}
if(section==="solicitudes"){const items=await db.select({id:inquiries.id,reference:inquiries.reference,status:inquiries.status,type:inquiries.type,notes:inquiries.notes,internalNotes:inquiries.internalNotes,notificationStatus:inquiries.notificationStatus,notificationError:inquiries.notificationError,createdAt:inquiries.createdAt,customer:customers.name,phone:customers.phone}).from(inquiries).innerJoin(customers,eq(inquiries.customerId,customers.id)).orderBy(desc(inquiries.createdAt));return <><Head title="Solicitudes" text="Busca, filtra y actualiza el seguimiento de cada cotización."/><Panel title="Bandeja de solicitudes"><InquiryTable items={items.map(item=>({...item,createdAt:item.createdAt.toISOString()}))}/></Panel></>}
if(section==="clientes"){const items=await db.select({id:customers.id,name:customers.name,email:customers.email,phone:customers.phone,contactPreference:customers.contactPreference,requests:sql<number>`count(${inquiries.id})::int`}).from(customers).leftJoin(inquiries,eq(customers.id,inquiries.customerId)).groupBy(customers.id).orderBy(asc(customers.name));const editing=items.find(item=>item.id===editId);return <><Head title="Clientes" text="Crea, edita y consulta los datos de tus clientes."/><div className="admin-grid"><Panel title={editing?"Editar cliente":"Nuevo cliente"}><ValidatedAdminForm action={saveCustomer} required={["name"]} submitLabel={editing?"Guardar cambios":"Crear cliente"} className="admin-form">{editing&&<input type="hidden" name="id" value={editing.id}/>}<AdminFormSection number="1" title="Datos del cliente" text="Registra el nombre y al menos una forma de contacto."><Field name="name" label="Nombre" value={editing?.name}/><AdminFormGrid><Field name="email" label="Correo electrónico" value={editing?.email??""}/><Field name="phone" label="Teléfono" value={editing?.phone??""}/></AdminFormGrid></AdminFormSection><AdminFormSection number="2" title="Preferencias de contacto" text="Elige el canal principal para comunicarse con el cliente."><label><span>Canal preferido</span><select name="contactPreference" defaultValue={editing?.contactPreference??"whatsapp"}><option value="whatsapp">WhatsApp</option><option value="phone">Teléfono</option><option value="email">Correo electrónico</option></select></label></AdminFormSection></ValidatedAdminForm></Panel><AdminDataTable columns={["Nombre","Contacto","Solicitudes","Acciones"]} rows={items.map(item=>({id:item.id,cells:[{primary:item.name,secondary:item.contactPreference??undefined},{primary:item.phone||"Sin teléfono",secondary:item.email??undefined},item.requests],searchText:`${item.name} ${item.phone??""} ${item.email??""}`,filterValue:item.contactPreference??"",editHref:`/admin/clientes?edit=${item.id}`,canDelete:item.requests===0}))} noun="clientes" searchPlaceholder="Buscar clientes..." filterPlaceholder="Todos los canales" filterOptions={[{value:"whatsapp",label:"WhatsApp"},{value:"phone",label:"Teléfono"},{value:"email",label:"Correo electrónico"}]} deleteAction={deleteCustomer}/></div></>}
if(section==="pedidos"){
  const [items,orderLineItems,clientItems,requestItems] = await Promise.all([
    db.select({id:orders.id,reference:orders.reference,status:orders.status,total:orders.total,deposit:orders.deposit,balance:orders.balance,createdAt:orders.createdAt,paymentMethod:orders.paymentMethod,paymentStatus:orders.paymentStatus,paymentProofAssetId:orders.paymentProofAssetId,customer:customers.name,email:customers.email}).from(orders).innerJoin(customers,eq(orders.customerId,customers.id)).orderBy(desc(orders.createdAt)),
    db.select({id:orderItems.id,orderId:orderItems.orderId,name:orderItems.nameSnapshot,quantity:orderItems.quantity,unitPrice:orderItems.unitPriceSnapshot,lineTotal:orderItems.lineTotal,personalization:orderItems.personalization,productImageUrl:mediaAssets.url,comboImageUrl:combos.imageUrl}).from(orderItems).leftJoin(productImages,and(eq(productImages.productId,orderItems.productId),eq(productImages.primary,true))).leftJoin(mediaAssets,eq(mediaAssets.id,productImages.mediaAssetId)).leftJoin(combos,eq(combos.id,orderItems.comboId)),
    db.select().from(customers).orderBy(asc(customers.name)),
    db.select({id:inquiries.id,reference:inquiries.reference}).from(inquiries).orderBy(desc(inquiries.createdAt)),
  ]);
  return <><Head title="Pedidos" text="Crea pedidos y da seguimiento hasta la entrega."/><div className="admin-grid"><Panel title="Nuevo pedido"><ValidatedAdminForm action={saveOrder} required={["customerId","subtotal"]} submitLabel="Crear borrador" className="admin-form"><AdminFormSection number="1" title="Cliente y solicitud" text="Relaciona el pedido con un cliente y, si corresponde, con una solicitud."><AdminFormGrid><label><span>Cliente <em>*</em></span><select name="customerId" required defaultValue=""><option value="" disabled>Selecciona un cliente</option>{clientItems.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label><span>Solicitud</span><select name="inquiryId" defaultValue=""><option value="">Sin solicitud</option>{requestItems.map(i=><option key={i.id} value={i.id}>{i.reference}</option>)}</select></label></AdminFormGrid></AdminFormSection><AdminFormSection number="2" title="Entrega" text="Define cómo y dónde se entregará el pedido."><AdminFormGrid><label><span>Modalidad</span><select name="fulfillment" defaultValue="pickup"><option value="pickup">Retiro</option><option value="delivery">Entrega</option></select></label><Field name="deliveryAddress" label="Dirección"/></AdminFormGrid></AdminFormSection><AdminFormSection number="3" title="Resumen económico" text="Registra los importes en dólares estadounidenses."><AdminFormGrid><Field name="subtotal" label="Subtotal (USD)" type="number"/><Field name="deliveryFee" label="Costo de entrega (USD)" type="number"/><Field name="deposit" label="Adelanto (USD)" type="number"/></AdminFormGrid></AdminFormSection><input type="hidden" name="status" value="draft"/></ValidatedAdminForm></Panel><section className="admin-panel order-dashboard-panel"><OrderTable items={items.map(item=>({...item,createdAt:item.createdAt.toISOString()}))} lines={orderLineItems.map(({productImageUrl,comboImageUrl,...line})=>({...line,imageUrl:productImageUrl??comboImageUrl}))}/></section></div></>}
if(section==="inicio"){const items=await db.select().from(homepageSections).orderBy(asc(homepageSections.sortOrder));const selectedKey=homepageSectionKeys.find(key=>key===editId);const existing=selectedKey?items.find(item=>item.key===selectedKey):undefined;const editing=selectedKey?{id:existing?.id,key:selectedKey,visible:existing?.visible??true,content:existing?.content}:undefined;const homeSections=homepageSectionKeys.map(key=>{const item=items.find(row=>row.key===key);return{key,visible:item?.visible??true,content:item?.content as Record<string,unknown>|undefined};});return <><header className="admin-head admin-home-content-head"><div><h1>Contenido del inicio</h1><p>Administra y organiza las secciones que aparecen en la página principal de OrosBlooms.</p></div><a className="admin-home-preview-link" href="/" target="_blank">Ver página de inicio ↗</a></header>{editing?<div className="admin-grid admin-home-editor-grid"><Panel title={`Editar: ${homepageSectionDefaults[editing.key].label}`}><HomepageSectionForm section={editing}/></Panel><HomepageContentManager sections={homeSections}/></div>:<HomepageContentManager sections={homeSections}/>}</>}
if(section==="servicios"){const[items,translationRow]=await Promise.all([db.select().from(services).orderBy(asc(services.sortOrder)),db.select({value:siteSettings.value}).from(siteSettings).where(eq(siteSettings.key,"service-translations")).limit(1)]);const translations=(translationRow[0]?.value??{}) as Record<string,{nameEn?:string;descriptionEn?:string}>;return <><Head title="Servicios" text="Administra los datos y la disponibilidad de los servicios."/><ServiceManager items={items} translations={translations}/></>}
if(section==="paginas"){const[pageRow,legacyRow,translationRow,serviceRows]=await Promise.all([db.select({value:siteSettings.value}).from(siteSettings).where(eq(siteSettings.key,"page-content")).limit(1),db.select({value:siteSettings.value}).from(siteSettings).where(eq(siteSettings.key,"service-page-content")).limit(1),db.select({value:siteSettings.value}).from(siteSettings).where(eq(siteSettings.key,"service-translations")).limit(1),db.select({id:services.id,slug:services.slug,type:services.type,name:services.name,description:services.description,imageUrl:mediaAssets.url}).from(services).leftJoin(mediaAssets,eq(services.imageId,mediaAssets.id))]);const saved=(pageRow[0]?.value??{}) as Record<string,Partial<PageContent>&{images?:PageImage[]}>;const legacy=(legacyRow[0]?.value??{}) as Record<string,Partial<PageContent>&{images?:PageImage[]}>;const translations=(translationRow[0]?.value??{}) as Record<string,{nameEn?:string;descriptionEn?:string}>;const content=Object.fromEntries(pageSlugs.map(key=>{const type=key==="bodas"?"wedding":key==="eventos"?"event":null;const service=type?serviceRows.find(item=>item.slug===key||item.type===type):undefined;const fallback=service?{titleEs:service.name,titleEn:translations[service.id]?.nameEn||service.name,descriptionEs:service.description||"",descriptionEn:translations[service.id]?.descriptionEn||service.description||""}:{};const value={...defaultPageContent(key),...fallback,...(service?legacy[service.id]:undefined),...saved[key]};if(!value.images&&service?.imageUrl)value.images=[{id:"legacy",url:service.imageUrl}];return[key,value];})) as Partial<Record<PageSlug,PageContent&{images?:PageImage[]}>>;return <><Head title="Páginas" text="Edita el contenido, las traducciones y las imágenes de cada página pública."/><PageContentManager content={content}/></>}
if(section==="seo-politicas"){const[row]=await db.select({value:siteSettings.value}).from(siteSettings).where(eq(siteSettings.key,"seo-policies")).limit(1);const defaults={siteTitleEs:"OrosBlooms",siteTitleEn:"OrosBlooms",descriptionEs:"Diseño floral para momentos que se recuerdan.",descriptionEn:"Floral design for moments worth remembering.",privacyEs:"",privacyEn:"",termsEs:"",termsEn:""};return <><Head title="SEO y políticas" text="Edita metadatos y documentos legales en español e inglés."/><Panel title="Contenido público"><SeoPoliciesForm value={{...defaults,...(row?.value as Partial<typeof defaults>|undefined)}}/></Panel></>}
if(section==="configuracion"){const[row]=await db.select({value:siteSettings.value}).from(siteSettings).where(eq(siteSettings.key,"business")).limit(1);const value={...testBusinessSettings,...(row?.value as Partial<BusinessSettings>|undefined)};return <><Head title="Configuración" text="Contacto, zona de entrega y condiciones comerciales públicas."/><Panel title="Datos del negocio"><BusinessSettingsForm value={value}/></Panel></>}
const mediaQuery=Array.isArray(queryParams.q)?queryParams.q[0]??"":queryParams.q??"";const items=mediaQuery?await db.select().from(mediaAssets).where(or(ilike(mediaAssets.alt,`%${mediaQuery}%`),ilike(mediaAssets.url,`%${mediaQuery}%`))).orderBy(desc(mediaAssets.createdAt)):await db.select().from(mediaAssets).orderBy(desc(mediaAssets.createdAt));return <><Head title="Multimedia" text="Carga, busca y administra los recursos visuales del sitio."/><div className="admin-grid"><Panel title="Nueva imagen"><ValidatedAdminForm action={uploadMedia} required={["file"]} submitLabel="Subir imagen" className="admin-form"><AdminFormSection number="1" title="Información de la imagen" text="Describe el recurso para facilitar su búsqueda y accesibilidad."><Field name="alt" label="Descripción de la imagen"/></AdminFormSection><AdminFormSection number="2" title="Archivo" text="Selecciona una imagen JPG, PNG o WebP."><label><span>Archivo <em>*</em></span><input name="file" type="file" accept="image/jpeg,image/png,image/webp" required/></label></AdminFormSection></ValidatedAdminForm></Panel><div className="product-table-workspace"><form className="product-table-filters admin-media-filters"><input name="q" defaultValue={mediaQuery} placeholder="Buscar por descripción"/><button>Buscar</button></form><section className="product-table-card"><table className="admin-table product-table"><thead><tr><th>Recurso</th><th>Origen</th><th>Visibilidad</th><th>Acciones</th></tr></thead><tbody>{items.map(item=><tr key={item.id}><td><div className="service-table-name"><strong>{item.alt||"Sin descripción"}</strong><small>{item.format?.toUpperCase()||"IMAGEN"}</small></div></td><td>{item.provider}</td><td><span className="product-table-status">{item.visibility}</span></td><td><AdminRecordActions id={item.id} deleteAction={deleteMediaAsset}/></td></tr>)}</tbody></table><footer><span>Mostrando {items.length} recursos</span></footer></section></div></div></>}
function Head({title,text}:{title:string;text:string}){return <header className="admin-head"><div><h1>{title}</h1><p>{text}</p></div></header>}function Panel({title,children}:{title:string;children:React.ReactNode}){const modal=/^(Nuevo|Nueva|Editar)/.test(title);return modal?<AdminFormModal title={title}>{children}</AdminFormModal>:<section className="admin-panel"><h2>{title}</h2>{children}</section>}function Field({name,label,type="text",textarea=false,value}:{name:string;label:string;type?:string;textarea?:boolean;value?:string}){const placeholder=type==="number"?"0":`Escribe ${label.toLowerCase()}`;const optional=['deliveryAddress','startsAt','endsAt','promotionalPrice','description','descriptionEs','descriptionEn','nameEn','sortOrder','email','phone','alt'];const required=!optional.includes(name);return <label><span>{label}{required&&<em>*</em>}</span>{textarea?<textarea name={name} defaultValue={value} placeholder={placeholder} required={required}/>:<input name={name} type={type} defaultValue={value} placeholder={placeholder} required={required} min={type==="number"?0:undefined} pattern={name==="slug"?"[a-z0-9-]+":undefined} title={name==="slug"?"Usa únicamente letras minúsculas, números y guiones.":undefined}/>}</label>}


